### PR TITLE
Makefile: Explicitly execute python3

### LINKED ISSUE #161: Can't build fonts on Debian 11 Bullseye
Dear dev,
when I try to build the font, I get this error:
```
$ make
Generating	build/EBGaramond08-Regular.otf
make: python: No such file or directory
make: *** [Makefile:53: build/EBGaramond08-Regular.otf] Error 127
```

All dependencies are installed:
```
$ apt policy python3-fontforge ttfautohint 
python3-fontforge:
  Installed: 1:20201107~dfsg-4
  Candidate: 1:20201107~dfsg-4
  Version table:
 *** 1:20201107~dfsg-4 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
ttfautohint:
  Installed: 1.8.3-2+b1
  Candidate: 1.8.3-2+b1
  Version table:
 *** 1.8.3-2+b1 500
        500 http://deb.debian.org/debian bullseye/main amd64 Packages
        100 /var/lib/dpkg/status
```

Maybe the above libraries are old?

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Fixes #161

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
`Internal Error: Attempt to output 850939 into a 16-bit field. It will be truncated and the file may not be useful.` 

appears to be a needless warning that's fixed in the latest FontForge release: https://github.com/fontforge/fontforge/issues/3009

**Comment by georgd** [comment]
Thanks for the PR. Before merging, I’ve got two questions:

- Does this work on Windows too, normally? I just checked on my Windows PC which doesn’t know about python3. But then, I couldn’t say if that’s normal because this is a very strict setup by my work IT which often behaves a bit differently than freer setups.
- Is the CI failure to be expected?
    ```
    github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/repos#delete-a-release-asset"}
    ```

**Comment by timgrei** [comment]
On Windows you would need to change it to ffpython.

**Comment by Alexander-Wilms** [comment]
Hm, seems it doesn't work OOTB on Windows. I'll have to investigate.

Yes, the CI failure is due to me not bein able to overwrite the artifact of your nightly tag. I'll open another PR that skips this CI step for PRs.

**Comment by georgd** [comment]
Thanks! You’re great!

**Comment by Alexander-Wilms** [comment]
Does it work for you now?

**Pull request merged**
