### PR TITLE
[Initials] Add M

### PR DESCRIPTION
**Pull request by astoeriko**
This pull request addresses part of https://github.com/georgd/EB-Garamond/issues/115 by adding the svg files for the M initial that I created from [this original](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10644).
I was able to build the otf files but not the rest of the font files. I think the problem is that I do not have all the required software installed to run all of the build script successfully. (I had a hard time finding out what is needed, maybe some hints in the readme would be helpful.) So it would be good if someone else could also check if everything works. 
Let me know what you think about my drawing – I sometimes found it difficult to figure out what are intentional ornaments and what is noise. I am particularly unsure about the small “hook” at the upper right part of the M letter. It looks intentional to me in the original drawing and is also present [in another copy of the same initial](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10083), but looks kind of uncommon to me.
M_10644
M_initial
M_F1
M_F2

### CODE REVIEW

**Comment by lutetiensis** [comment]
Great! Thank you so much!

A couple things:
- if you look at the original A/F/L/T, it looks like the top and the bottom of the letters are aligned on horizontal lines (green lines below). It seems all the lines should be straight as well.
- the blue part seems to square.
- inside the red square, I think something is missing on the right side to make it symmetric. We can barely see it in the original, but I think it's there, I'd add it.
- I agree the hook is weird. I would remove it to make it similar to the N.
- Can you clean your SVGs? ```<defs/>```, ```<<sodipodi:namedview/>```, ```<metadata/>```, as well as the ```inkscape:*```, ```sodipodi:*``` and ```style``` attributes should disappear. This will make sure your SVG is minimal and therefore more "standard".

M

**Comment by lutetiensis** [comment]
> I was able to build the otf files but not the rest of the font files. I think the problem is that I do not have all the required software installed to run all of the build script successfully. (I had a hard time finding out what is needed, maybe some hints in the readme would be helpful.) So it would be good if someone else could also check if everything works.

You will need ```[ttfautohint](https://www.freetype.org/ttfautohint/)``` and ```[sfnttool.jar](https://github.com/daltonmaag/sfntly-py)```. The latter is used to build ```woff``` and ```eot``` files, I am sure we replace it with newer alternatives (fontforge can already generate woff files).

I have everything working on my setup and tested your branch, everything works fine.

**Comment by astoeriko** [comment]
Thanks for your feedback, @lutetiensis! I addressed the issues you brought up in my recent commit. The updated letter now looks like this.
M

**Comment by lutetiensis** [comment]
Much better, thank you very much!

1. The right half of the M doesn't seem straight. You can probably drop the anchor points along the paths.

2. There are still some ```stroke-width``` attributes.

Otherwise I think it's ready to go in! Thanks again!

**Comment by doctorlard** [comment]
Looks great, let's merge it 😄

**Pull request merged**
