### PR TITLE
Initials P, I, J, R and K

### PR DESCRIPTION
**Pull request by timgrei**
Someone definitely needs to rework the letters, but I think that's a good base.
I had a document, where I have listed the sources. Unfortunately, my hard drive is broken, so I can't tell you which originals I used. For J and K I used elements from unused alternative backgrounds of letters already done.

### CODE REVIEW

**Comment by timgrei** [comment]
| SVG | Original|
|--------|--------|
| | [](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=9720) |
|  | [](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10683) |
|  | [](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10168) |

**Comment by timgrei** [comment]
For J I used a D

|   |[](http://www.bvh.univ-tours.fr/batyr/beta/notice_bois.php?IdBois=10414) |
------------------|------

**Comment by timgrei** [comment]
I'm also working on S, H, E, W and X.

**Comment by timgrei** [comment]
I now have prototypes for all remaining letters, including umlauts.

**Comment by Twey** [comment]
I'd just like to thank you personally, I'm using these initials on my personal website and the lack of initials for some letters has been bugging me for some time!

**Comment by georgd** [comment]
@timgrei thank you very much!

**Comment by timgrei** [comment]
@georgd If you would merge [#117](https://github.com/georgd/EB-Garamond/pull/117) and [#119](https://github.com/georgd/EB-Garamond/pull/119), I could try to make the corrections, you suggested. Also [#120](https://github.com/georgd/EB-Garamond/pull/120), if there is something wrong with it.

**Comment by georgd** [comment]
Done.

**Pull request merged**
